spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

websiteUrl: http://unishare.com